### PR TITLE
add whatsnew and test coverage

### PR DESCRIPTION
**Pull request by bjlittle**
### Description
Hey @krikru,

As promised, here's some updates that's targeting your `patch-1` branch, which is the source of the pull-request https://github.com/SciTools/iris/pull/4894.

It basically adds a suitable entry to our documentation `whatsnew`, plus we blow the trumpet that it's your first contribution to `iris` :smile: 

I've also added a couple of tests to exercise the change in behaviour, which is based on a pull-request (now closed and unmerged) by @rcomer, see https://github.com/SciTools/iris/pull/4136.

To be transparent and fair, I've also acknowledged @rcomer's contribution in the `whatsnew` along side yourself.

Here is proof that the [ci-tests](https://github.com/bjlittle/iris/actions/runs/2826229475) are passing for this change from my fork of `iris`.

If you're happy with my suggestions, then simply merge this pull-request, and it will automatically become part of your associated pull-request on `iris`.

At that point, I think we're good to bank this goodness in time for the `iris` 3.3 release :+1: 

---
[Consult Iris pull request check list]( https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_pull_request_checklist.html)

### CODE REVIEW

**Comment by krikru** [comment]
@bjlittle The tests look good to me. Maybe you could also do `self.assertIs(gcs.colorbar.ax, ax1)` in `test__with_axes` (I guess a similar line could be added in `test__without_axes`, but that requires `_plot` to also return the `Axes` object that is returned by `fig2.add_subplot(1, 1, 1)`)? I'm just assuming that `gcs.colorbar.ax` should be the `Axes` object you specified when calling `qplt.contourf` (if you do specify one), but maybe it's not.

It looks like `test__with_axes` is the test that checks for the bug. Have you tested that it triggers the bug that I described when you don't have the fix, and that it doesn't trigger it when you do have the fix?

**Comment by bjlittle** [comment]
Hey @krikru, 

I like your thinking... but just for clarity, the `gcs.colorbar.ax` isn't the axes that you think it might be, it's an entirely different axes, but I totally get your intent.

So I've pushed a change which does as you suggested, but the axes information that we need is squirreled away somewhere differently within `matplotlib`. However, with a little bit of detective work it was reasonably straight forward to understand the internal plumbing.

And yeah, `test_quickplot.TestSubplotColorbar.test__with_axes` is specifically targeting your fix. Whereas `test_quickplot.TestSubplotColorbar.test__without_axes` is testing the status-quo (aka default behaviour).

Consequently, when I remove your fix to `iris.quickplot._label` the `test_quickplot.TestSubplotColorbar.test__with_axes` fails, as we might expect :+1:

**Comment by bjlittle** [comment]
Also, here is the latest [ci-tests](https://github.com/bjlittle/iris/actions/runs/2828504131) run on my repo for the latest change.

**Review by krikru — APPROVED** [review]
Looks good

**Comment by bjlittle** [comment]
Just rerunning the tests after the last refactor, see https://github.com/bjlittle/iris/actions/runs/2828606527

**Comment by bjlittle** [comment]
@krikru Once you merge this, then I'll bank https://github.com/SciTools/iris/pull/4894 :+1:

**Comment by krikru** [comment]
Okay, merging now

**Pull request merged**
